name: Pull request
on:
    pull_request:
        types: [review_requested, opened, reopened, synchronize]
        branches:
            - main-fyve

jobs:
    testing:
        uses: ./.github/workflows/fyve_testing.yml
        with:
          call-source: pull_request
        secrets: inherit
    coverage:
        #  https://docs.github.com/en/actions/quickstart
        needs: testing
        uses: ./.github/workflows/fyve_coverage.yml
        with:
          call-source: pull_request
